version: "3"
services:
  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db

    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8
    ports:
      - 7101:7101
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    volumes:
      - ./db/users:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7201:3306
